apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generated/role.yaml
- role.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- rolebinding.yaml
- deployment.yaml
configurations:
- kustomizeconfig/nameprefix.yaml
configMapGenerator:
- name: relay-node-tainter-controller-config
  files:
  - _examples=configmap-config-_examples.txt
commonLabels:
  app.kubernetes.io/name: relay-node-tainter
  app.kubernetes.io/component: controller
  app.kubernetes.io/instance: relay-node-tainter-controller
