apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: relay-node-tainter-controller
rules:
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, list, watch, create, update, delete]
