apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: relay-node-tainter-controller
subjects:
- kind: ServiceAccount
  name: relay-node-tainter-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: relay-node-tainter-controller
